server:
  port: 8084

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:mysql://localhost:3306/document_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  claim-service:
    url: http://localhost:8082
  auth-service:
    url: http://localhost:8081

file:
  upload-dir: C:/claimswift/uploads
  max-size: 5MB

jwt:
  secret: mysecretkeymysecretkeymysecretkey_1234